### ISSUE TITLE
Add a link to the TMI Hall of Fame

### ISSUE THREAD

**Issue by NottCurious** [NottCurious/TMIndiaBot#26]

**Comment by NottCurious** [comment]
https://tinyurl.com/TMIndiaLB

Hall of Fame Leaderboard ^

**Comment by NottCurious** [comment]
If possible we can also show the excel file in an embed

**Comment by PracticalMetal** [comment]
Hey! I would like to work on this, can explain what the issue is?

**Comment by NottCurious** [comment]
Hey!
We need a slash command in the generic cog that puts the hall of fame link in an embed

py-cord doesn't not currently have docs for it's development branch that we're currently using, so you might have to take the other commands in the cogs as examples.

when the user uses the command it needs to respond with the link in an embed, preferably like in the image shown below.
![image](https://user-images.githubusercontent.com/56356841/145332069-42d3fec1-73fb-4a98-912a-08d5094e8001.png)
